### ISSUE TITLE
Outdated stack.yaml

### ISSUE THREAD

**Issue by Emmatipate** [jaor/xmobar#357]
When I tried to build using `stack build --flag xmobar:all_extensions` I got several errors that all had to do with library versions.

I changed my stack.yaml to this
```
resolver: lts-12.1
packages:
- .
extra-deps:
- iwlib-0.1.0
- parsec-numbers-0.1.0
- alsa-mixer-0.2.0.3
```

Cabal also warned me about `Paths_xmonad` not being in xmobar.cabal's other-modules. (Is this intentional? Package management in haskell still confuses me.)

**Comment by jaor** [comment]
Thanks for the hints.  To be honest, I don't really know how to use
stack properly, and just put in stack.yaml what kind people like you
send my way :)

I don't understand that Cabal warning either.  Although most people use
xmobar with xmonad, the two code bases are totally separate and xmobar
doesn't use any xmonad library, so perhaps it's something in your local
configuration?

**Comment by Emmatipate** [comment]
Oops I meant to say Paths_xmobar not xmonad. I mixed up the names :)

**Comment by jaor** [comment]
On Wed, Jul 18 2018, Emil Segerbäck wrote:

> Oops I meant to say Paths_xmobar not xmonad. I mixed up the names :)

Oh yes, i see it now. I've added the module to the cabal file to avoid
the warning.  I'll wait/investigate a bit to upgrade the stack.yaml file
in case someone reading this that is more knowledgeable on stack gives
us more feedback (i am not sure if we should worry about the needed
extra-deps).

**Comment by Emmatipate** [comment]
I also just ran into #354 so I had to change my stack.yaml again to prevent the segfault. lts-11.17 was the latest lts for GHC 8.22 but that did not include dbus-1.0.1 so I had to add that to extra-deps as well.

**Comment by osa1** [comment]
> I also just ran into #354 so I had to change my stack.yaml again to prevent the segfault. lts-11.17 was the latest lts for GHC 8.22 but that did not include dbus-1.0.1 so I had to add that to extra-deps as well.

Do you mean the segfault disappears with GHC 8.2.2? That's a very valuable information.

**Comment by Emmatipate** [comment]
> Do you mean the segfault disappears with GHC 8.2.2? That's a very valuable information to debug #354.

Yes, some people in the 354-thread said they didn't experience the crash with 8.2.2 so I tried and it's been stable so far

**Comment by osa1** [comment]
Indeed, I was able to reproduce this behavior as well. Thanks.

**Comment by ThomasLocke** [comment]
I've just compiled xmobar using stack and this stack.yaml

```yaml
resolver: lts-12.24
packages:
- .
extra-deps:
- iwlib-0.1.0
- parsec-numbers-0.1.0
- alsa-mixer-0.2.0.3
- libmpd-0.9.0.9
```

It compiled without errors and so far it is working fine. Resolver 12.24 is GHC 8.4.4, which should not suffer from the same bug as GHC 8.4.3 AFAIK. At least I have not suffered any xmobar crashes yet. Might need some more testing, but if it works it might be worth adding 8.4.4 to the list of GHC's that work.  :)

**Comment by awittenb** [comment]
@ThomasLocke Thanks! Also wanted to add that I needed to install `libasound2` for alsa and `libiw-dev` for iw in case others are looking for the correct packages on Ubuntu.

**Comment by jaor** [comment]
Thanks for the updates!  I've pushed a new stack.yaml that uses the
recently released lts-13.0, which, combined with an upgrade to
alsa-mixer 0.3.0 makes iwlib the only needed extra-deps.  I've also
commented the yaml file indicating what's needed for lts-12.4.  Please
let me know if you see anything wrong.

**Comment by cirquit** [comment]
For other who may still have this issue, I successfully installed xmobar from a minimal ubuntu mate 18.04 install with the lts-12.24 and all extra-deps:

```
> sudo apt-get install libiw-dev
> sudo apt-get install libxml2-dev
> sudo apt-get install libxpm-dev
> sudo apt-get install libasound2-dev
> stack install
```
