### ISSUE TITLE
Xmobar creating stray ~/.xmobar directory

### ISSUE THREAD

**Issue by annacrombie** [jaor/xmobar#405]
This behavior started after I updated xmobar, but I do not know which version I was using previously.  Currently, I am using 0.31.

Basically I have my xmobarrc at `$XDG_CONFIG_HOME/xmobar/xmobarrc`.  When I run xmobar for the first time, it reads that config and everything works as expected, except that it also creates an empty directory `~/.xmobar`.  Now, the next time I try to run xmobar it tries to read my config from that empty directory, fails, and opens with the default configuration.  Currently I have to manually remove this file after I run xmobar.

If you don't have time, I could probably submit a PR.  It has been quite awhile since I did some haskell though.

**Comment by jaor** [comment]
hi, in what you describe, you're always running xmobar without any
arguments, right?

**Comment by annacrombie** [comment]
Actually, xmobar usually gets run by the statusBar function in my xmonad.hs

```hs
xmonad =<< statusBar "xmobar" myPP myToggleStrutsKey myConfig
```

I assume it is run without any arguments though.  I can also reproduce the problem by running xmobar manually with no arguments.

So basically yes, I am always running xmobar without any arguments.

**Comment by jaor** [comment]
thanks for the confirmation.  i will take a look when i have a moment,
it shouldn't be difficult to fix.

**Comment by jaor** [comment]
@annacrombie, i've just pushed a patch that i think fixes this
problem: is it possible for you to try with the master branch?

**Comment by annacrombie** [comment]
It works!  Thank you

**Comment by ikn** [comment]
This is still an issue for me, and as far as I can tell I'm running the latest Git version.  I'm using the [`xmobar-git`](https://aur.archlinux.org/packages/xmobar-git/) package from AUR on Arch Linux.  Hopefully this shell session has enough information:

```
$ pacman -Q xmobar
xmobar-git 0.31.r20.gd5feb7f-1

$ xmobar --version
xmobar 0.32
 (C) 2007 - 2010 Andrea Rossato 
 (C) 2010 - 2019 Jose A Ortega Ruiz
 <mail@jao.io>

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the License for more details.

$ stat ~/.config/xmobar/
  File: /home/j/.config/xmobar/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 802h/2050d	Inode: 3206        Links: 2
Access: (0755/drwxr-xr-x)  Uid: ( 1000/       j)   Gid: (  100/   users)
Access: 2014-12-22 18:17:23.000000000 +0000
Modify: 2018-02-09 22:39:08.993776132 +0000
Change: 2018-02-09 22:39:08.993776132 +0000
 Birth: 2014-12-22 18:19:20.254878806 +0000

$ stat ~/.xmobar/
stat: cannot stat '/home/j/.xmobar/': No such file or directory

$ xmobar
^CAsyncCancelled
^C

$ stat ~/.xmobar/
  File: /home/j/.xmobar/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 802h/2050d	Inode: 1835050     Links: 2
Access: (0755/drwxr-xr-x)  Uid: ( 1000/       j)   Gid: (  100/   users)
Access: 2019-10-15 19:00:55.923664188 +0100
Modify: 2019-10-15 19:00:55.923664188 +0100
Change: 2019-10-15 19:00:55.923664188 +0100
 Birth: 2019-10-15 19:00:55.923664188 +0100
```

When starting xmobar with `~/.xmobar` already existing, it ignores my config in `~/.config/xmobar`.

**Comment by jaor** [comment]
i cannot reproduce this issue following your same procedure.  is there
anyway that pacman can tell you the git hash it's using? for the record,
it should be at least 5f10530.

thanks

**Comment by ikn** [comment]
The first command I ran shows the package version, which is generated from the checked-out git repository at build-time.  The `d5feb7f` part of this is the short git commit (like in `git describe`).  I'm probably doing something wrong somewhere, but I'm not familiar enough with Haskell build systems to know what to investigate - is there any way I can verify that the built version has a particular change, or was built from a particular git commit?

**Comment by jaor** [comment]
hmm, if it's d5feb7f then it's indeed the head of this repo, so it should be working.  to check if the version is new enough, maybe you could try one of the latest features in your config... e.g., using "-P" in the additional argument list of the Battery monitor, if you're using it (that should cause <left> to include a % sign).

**Comment by jaor** [comment]
oh wait, it says version 0.32, so it's indeed new enough. now i'm a bit puzzled. please let me try to reproduce this again on my side, i must be missing something.

**Comment by jaor** [comment]
reproduced (needs actual content in .config/xmobar, i hadn't that).  reopeining, will look into it. thanks a lot for checking!

**Comment by ikn** [comment]
Thanks, it's good to know I haven't gone crazy.

**Comment by jaor** [comment]
nah, i'm probably nearer to that than you.  please see if you can try
the latest master (2389050, seems that should be more or less automatic
with pacman?), and wether it really fixes the issues.  thanks a bunch!

**Comment by ikn** [comment]
Works perfectly.  Thanks a lot for the quick fix.

**Comment by jaor** [comment]
perfect, thanks for checking.
