### ISSUE TITLE
StdinReader reports EOF error

### ISSUE THREAD

**Issue by slotThe** [jaor/xmobar#442]
Starting with commit b7a3d674581720bfb63bf73cae8368ebbad81004 (#439), xmobar---when started from xmonad---now reports an error on the `StdinReader`: 

    xmobar: Received exception <stdin>: hGetLine: end of file

Before this commit, things work perfectly.  This seems to happen with the default xmobar configuration as well.

Minimal xmonad configuration to reproduce this:

```haskell
{-# LANGUAGE NamedFieldPuns #-}

import XMonad
import XMonad.Hooks.DynamicLog (statusBar)

main :: IO ()
main = xmonad
   =<< statusBar "xmobar"
                 def
                 (\XConfig{ modMask } -> (modMask, xK_b))
                 def
```

The `statusBar` function basically takes care of the whole `spawnPipe` shenanigans.  

I'm sort of pressed for time right now, so I don't have much time to investigate this (i.e. starting xmobar manually via `spawnPipe` etc.).  Just wanted to have something to go off of for later debugging.

**Comment by jaor** [comment]
@psibi so it seems this is the scenario the exception handler was trying to prevent.  it seems we need to ignore, at least, EOF exceptions, no?

**Comment by psibi** [comment]
@jaor Probably, but I think we need to understand where the exception is arising from and see if we need to ignore EOF exception.

@slotThe I Just tried the above configuration of yours and it didn't throw exception for me. So, unfortunately I cannot debug this further without help from you. Can you add more details:
* Which platform you are using ?
* What is your xmobar configuration ?

**Comment by psibi** [comment]
@slotThe Also, does the exception occur as soon as you start your xmonad instance or does it take some time for it to receive the exception ?

**Comment by psibi** [comment]
Also, are you able to reproduce the behaviour with the following xmonad configuration:
```
{-# LANGUAGE NamedFieldPuns #-}

import XMonad
import XMonad.Hooks.DynamicLog (statusBar)

main :: IO ()
main = xmonad
   =<< statusBar "xmobar"
                 (def { ppTitle = \_ -> "hello world"})
                 (\XConfig{ modMask } -> (modMask, xK_b))
                 def
```

**Comment by slotThe** [comment]
Thanks for the responses!

>     * Which platform you are using ?

I'm using Void Linux (which does use some non-standard software, like musl libc).  I have, however, also been able to reproduce this on another system running openSUSE Tumbleweed (which uses glibc) with the same xmonad config (and also the one below) and no xmobar config.

>     * What is your xmobar configuration ?

I've been able to reproduce this with no xmobar configuration (i.e. just using the defaults xmobar sets) and hence all my testing was done with no config whatsoever.

> @slotThe Also, does the exception occur as soon as you start your xmonad instance or does it take some time for it to receive the exception ?

It's instant, I don't see my workspaces/whatever else xmonad feeds to xmobar via the named pipe at any point.

> Also, are you able to reproduce the behaviour with the following xmonad configuration:
>
> [...]

Yup, same issue.

**Comment by psibi** [comment]
@slotThe Can you try this with this xmobarc configuration (by placing it under `~/.xmobarrc` ) and see if the issue is still reproducible:
```
Config { font = "xft:Ubuntu Mono:size=12:bold:antialias=true"
       , bgColor = "black"
       , fgColor = "grey"
       , position = TopW L 100
       , lowerOnStart = False
       , hideOnStart = False
       , overrideRedirect = True
       , allDesktops = True
       , commands = [
                     Run StdinReader
                    , Run Date "%a %b %_d %l:%M" "date" 10
                    ]
       , sepChar = "%"
       , alignSep = "}{"
       , template = "%StdinReader% | <fc=#ee9a00>%date%</fc>"
       }
```

@jaor Can somebody use xmobar without any configuration ? I wasn't aware of that before.

**Comment by jaor** [comment]
On Tue, May 05 2020, Sibi Prabakaran wrote:

> @slotThe Can you try this with this xmobarc configuration (by placing it under ~/.xmobarrc ) and see if the
> issue is still reproducible:
>
> Config { font = "xft:Ubuntu Mono:size=12:bold:antialias=true"
>        , bgColor = "black"
>        , fgColor = "grey"
>        , position = TopW L 100
>        , lowerOnStart = False
>        , hideOnStart = False
>        , overrideRedirect = True
>        , allDesktops = True
>        , commands = [
>                      Run StdinReader
>                     , Run Date "%a %b %_d %l:%M" "date" 10
>                     ]
>        , sepChar = "%"
>        , alignSep = "}{"
>        , template = "%StdinReader% | <fc=#ee9a00>%date%</fc>"
>        }
>

> @jaor Can somebody use xmobar without any configuration ? I wasn't aware of that before.

yes, there is a default configuration. and we must support it.

orthogonally, if xmobar is reading from a pipe, and the other end has
the means to reopen it (which i guess would involve sending EOF), i
don't see why we wouldn't support it by retrying on EOF.  at least a few
times.

**Comment by psibi** [comment]
@jaor Sure, we should definitely support it. I'm just trying to understand the root cause of the EOF!

**Comment by jaor** [comment]
On Tue, May 05 2020, Sibi Prabakaran wrote:

> @jaor Sure, we should definitely support it. I'm just trying to
> understand the root cause of the EOF!

yeah, that puzzles me too a bit.  to be honest, i've got the feeling
that by retrying we're working around some external deficiency (perhaps
in some library or another), but since we've been masking it so far,
we're condemned to keep doing it :)

**Comment by psibi** [comment]
@slotThe Can you try your xmonad-contrib with this one which I have currently pushed in a specific branch: https://github.com/psibi/xmonad-contrib/tree/debug-xmobar and see if you are still getting the exception ?

**Comment by slotThe** [comment]
> @slotThe Can you try this with this xmobarc configuration (by placing it under `~/.xmobarrc` ) and see if the issue is still reproducible:
> 
> [...]

Aha, making progress!

So it works with that configuration.  Apparently, the offending option is `lowerOnStart`.  Whenever this is set to `True` (as is the case in the default configuration and also my personal one) the EOF error seems to occur.  If I set it to `False`, everything works just fine.

The actual function calls (via the X11 lib) `XLowerWindow` ( docs: https://tronche.com/gui/x/xlib/window/XLowerWindow.html ).  Now, why this should cause that specific but I have absolutely no idea...

**Comment by psibi** [comment]
@slotThe That's some nice debugging. Nice to know that it's not an issue with xmonad-contrib. I will try to look into more on why it's happening. :-)

**Comment by psibi** [comment]
@slotThe I tried with `lowerOnStart = True`, on my machine and I wasn't able to reproduce. I guess this might be something related to mus. Can you check in your openSUSE system to see if the issue is reproducible with/without `lowerOnStart` ?

**Comment by slotThe** [comment]
On Fri, May 08 2020 07:17, Sibi Prabakaran wrote:
> @slotThe I tried with `lowerOnStart = True`, on my machine and I
> wasn't able to reproduce. I guess this might be something related to
> mus. Can you check in your openSUSE system to see if the issue is
> reproducible with/without `lowerOnStart` ?

Yup, can conform that it's also happening on the openSUSE system with
just

```
Config { lowerOnStart = True }
```

as my `.xmobarrc`.  With it set to `False` I get normal behaviour (same
as on Void).

**Comment by psibi** [comment]
@slotThe Interesting. That confirms that the issue isn't with the musl environment. Do you run xmonad directly under X11 server or is it different ? What is your setup ?

Also, after the exception happens - can you see the logs under `~/.xsession-errors` and find the relevant message before (or even after) this line:
```
xmobar: Received exception <stdin>: hGetLine: end of file
```
I want to see if that gives us any further clue.

**Comment by slotThe** [comment]
On Fri, May 08 2020 08:39, Sibi Prabakaran wrote:
> Do you run xmonad directly under X11 server or is it different ? What
> is your setup ?
>

I pretty much run it directly under X, yes (I just have `exec xmonad` in
my .xinitrc and start the X server manually via `startx`).

> Also, after the exception happens - can you see the logs under
> `~/.xsession-errors` and find the relevant message before (or even
> after) this line:
> ```
> xmobar: Received exception <stdin>: hGetLine: end of file
> ```
> I want to see if that gives us any further clue.
>

Oooh, this is very interesting indeed!

Logs with the broken xmobar:

```
"xmobar: Received exception <stdin>: hGetLine: end of file"
connectSession: DBUS_SESSION_BUS_ADDRESS is missing or invalid.
xmobar: Prelude.!!: index too large
<file descriptor: 4>: commitBuffer: resource vanished (Broken pipe)
<file descriptor: 4>: commitBuffer: resource vanished (Broken pipe)
<file descriptor: 4>: commitBuffer: resource vanished (Broken pipe)
[this repeats for a while]
```

Logs with a working xmobar:

```
connectSession: DBUS_SESSION_BUS_ADDRESS is missing or invalid.
"xmobar: Received exception <stdin>: hGetLine: end of file"
```

So it receives the error in either case, but it's able to recover from
it when it's not at the bottom of the window stack.  That exception on
`(!!)` seems to kill it for good.

Generously sprinkling some traces across various uses of `!!` reveals
the error to originate from two places; `Xmobar.App.EventLoop`, line
267:

```haskell
      getCoords (Text s,_,i,a) = textWidth d (fs!!i) s >>= \tw -> return (a, 0, fi tw)
```

and `Xmobar.X11.Draw`, line 58:

```haskell
        textWidth d (fs!!i) s >>= \tw -> return (Text s,cl,i,fi tw)
```

At some point, `i` is 1 but the length of `fs` is also just 1, leading
to the error.

I sadly know very little about the interfacing of X11 and xmobar, so
hopefully someone who knows what they're doing can weigh in here :)

**Comment by psibi** [comment]
@slotThe Nice! That's awesome debugging. I think we are closing down on the culprit. :-) I will look into this more.

@jaor It seems the issue is with `!!` incorrectly getting called somewhere in xmobar.

**Comment by psibi** [comment]
@slotThe I have a way of reproducing it in my system and I kind of understand why the issue is happening. But I'm not sure why it's happening in your system yet. Are you starting any program which sends the following data to the xmobar program via StdinReader:
```
<fn=1>
```
Note that it can be any number apart from 1. To debug it further, can you sprinkle more traces inside the `updateString` function in the `EventLoop.hs` module. Basically something like this:
```
updateString conf v = do
  s <- readTVarIO v
  print s
  let l:c:r:_ = s ++ repeat ""
  liftIO $ mapM (parseString conf) [l, c, r]
```

And can you let me know the logs from it during the crash ? Thanks!

**Comment by slotThe** [comment]
Oh I just realized what happened---I forgot to switch out my xmonad 
config with the testing one!  Obviously then one will get errors due to
xft being disabled.  Trying with the minimal config again, I don't see 
any more errors in my .xsession-errors file than in the working case.
So sorry for the red herring...

**Comment by psibi** [comment]
> Obviously then one will get errors due to xft being disabled. 

I don't think there was any errors because of "xft". I think if you open the following file in the browser, it will lead to a crash:

```
<!DOCTYPE html>
<html>

<head>
  <title>hello <fn=1>string</fn> </title>
</head>

<body>
dummy content
</body>

</html>
```

**Comment by slotThe** [comment]
On Fri, May 08 2020 13:18, Sibi Prabakaran wrote:
> I don't think there was any errors because of "xft". I think if you
> open the following file in the browser, it will lead to a crash:
> [...]
>

Sorry, I should have been more careful with my language there.  There
was an error because my config tried to output something to the bar that
used an alternative font (which was an xft font but that's completely
unrelated to the main point).

The html file does indeed cause the bar to crash (for pretty much the
same reason---maybe it's worth adding "fn" to the stripped items in
X.H.DynamicLog.xmobarStrip?), but my main point was that this issue
seems to be completely orthogonal to the actual bug.

**Comment by psibi** [comment]
@slotThe Ah, I see. So, there are two bugs here now. I will file a separate issue for it.

Okay, one question (sorry if you have mentioned the answer before):
* Is the bug reproducible on openSUSE with the proper minimal configuration with the buggy `lowerOnStart` field ?

**Comment by slotThe** [comment]
On Fri, May 08 2020 18:10, Sibi Prabakaran wrote:
> * Is the bug reproducible on openSUSE with the proper minimal
> configuration with the buggy `lowerOnStart` field ?

Yup, behaves in exactly the same way.

**Comment by psibi** [comment]
@slotThe Does the following configuration also reproduce the issue:

```
Config { lowerOnStart = True, overrideRedirect = False }
```

**Comment by psibi** [comment]
@slotThe One more question: Which ghc are using it to compile both xmonad and xmobar in Void Linux and openSUSE ?

Since the issue seems to be occurring on calling the function `lowerWindow` - I'm guessing if it's because of some FFI issues.

**Comment by slotThe** [comment]
On Sat, May 09 2020 07:45, Sibi Prabakaran wrote:
> @slotThe Does the following configuration also reproduce the issue:
>
> ```
> Config { lowerOnStart = True, overrideRedirect = False }
> ```
>

It does not, that configuration works.  However, that's due to the fact
that with those settings `lowerOnStart` actually gets set to false!  The
whole config gets run through `Xmobar.App.Opts.doOpts` which sets
`lowerOnStart` to

```haskell
  lowerOnStart = lowerOnStart conf && overrideRedirect conf
```

On Sat, May 09 2020 08:53, Sibi Prabakaran wrote:
> @slotThe One more question: Which ghc are using it to compile both
> xmonad and xmobar in Void Linux and openSUSE ?
>

I'm using ghc 8.8.3 on both systems.

**Comment by psibi** [comment]
Thanks, good catch. I don't think I would be able to help much as I'm not able to reproduce this at my end.

**Comment by jaor** [comment]
On Sun, May 10 2020, Sibi Prabakaran wrote:

> Thanks, good catch. I don't think I would be able to help much as I'm
> not able to reproduce this at my end.

should we then revert the bit that disables the monitor on EOF? or do we
have some other workaround?

**Comment by psibi** [comment]
@jaor I don't think reverting should be the proper behaviour as the origin of exception seems to be a call to `xLowerWindow`. I think the other monitors in xmobar (I haven't seen the code) isn't receiving the exception because they might be catching `SomeException`.

> or do we have some other workaround?

The workaround is to to set `lowerOnStart = False` as default value. But I'm not sure if we should do that.

**Comment by psibi** [comment]
We should probably see if others hit this and then make a decision. I would be curious to know if you are able to reproduce the issue. :-)

**Comment by jaor** [comment]
On Sun, May 10 2020, Sibi Prabakaran wrote:

> We should probably see if others hit this and then make a decision. I
> would be curious to know if you are able to reproduce the issue. :-)

i don't use xmobar or the stdinreader, so it's a bit of set up for me to
try.  while i agree we should get to the bottom of this, in the mean
time this is a regression for people like slotThe, in that their xmobar
is simply not working anymore (while the original issue had a real
workaroud: fixing the environment).

(and with this in master, i cannot release any new versions of xmobar)

**Comment by jaor** [comment]
On Sun, May 10 2020, Sibi Prabakaran wrote:

> The workaround is to to set lowerOnStart = False as default value. But
> I'm not sure if we should do that.

the default of that is to make some people configs just work with their
wms, we cannot change it without breaking other configurations.

**Comment by psibi** [comment]
@slotThe I think there is one more thing which we haven't tried: Can you compile your xmobar with profiling enabled so that we can get proper stack trace in `~/.xsession-errors` ?

If you are using stack, you can use the info here: https://stackoverflow.com/questions/47122303/how-to-get-stacktraces-with-stack-and-ghci

**Comment by slotThe** [comment]
On Sun, May 10 2020 18:47, Sibi Prabakaran wrote:
> The workaround is to to set `lowerOnStart = False` as default
> value. But I'm not sure if we should do that.
>

Indeed, I have a specific use-case for this feature (which is why I'm
using it in the first place): xmonad's scratchpads; most of the time,
I want these to cover the bar.  However, if I restart xmonad for one
reason or another and `lowerOnStart` is set to `False`, the bar will be
drawn above the scratchpads.  It also becomes impossible to hide the bar
via a keybinding.  Windows will try to occupy the space the bar takes,
but because it spawns on top of the window stack, they just slide under
the bar.

On Mon, May 11 2020 05:25, Sibi Prabakaran wrote:
> @slotThe I think there is one more thing which we haven't tried: Can
> you compile your xmobar with profiling enabled so that we can get
> proper stack trace in `~/.xsession-errors` ?
>

Sure, there you go: https://paste.rs/jTo

**Comment by psibi** [comment]
@slotThe That's quite helpful! Question:

Have you enabled dbus plugin of xmobar ? If yes, can you disable them and see if the bug is still reproducible.

**Comment by slotThe** [comment]
On Tue, May 12 2020 13:43, Sibi Prabakaran wrote:
> Have you enabled dbus plugin of xmobar ? If yes, can you disable them
> and see if the bug is still reproducible.
>

Oh yeah, xmobar is compiled with the `all_extensions` flag by default,
which includes dbus.  I can still reproduce the issue when compiling
xmobar without it.

New stack trace: https://paste.rs/HdQ

**Comment by psibi** [comment]
@slotThe Excellent debugging. I think this gives me enough information to debug this further. I will look over this in further detail and give you an update. Thanks!

**Comment by psibi** [comment]
@slotThe I have created a MR which modifies Timer.hs code: https://github.com/jaor/xmobar/pull/445

Can you test with that (again with dbus disable) and report me if you are able to reproduce the issue ? If you are able to reproduce the issue, I would like to see the stack trace as usual. Thanks!

**Comment by slotThe** [comment]
On Wed, May 13 2020 07:33, Sibi Prabakaran wrote:
> @slotThe I have created a MR which modifies Timer.hs code:
> https://github.com/jaor/xmobar/pull/445
>

Thank you so much for trying so hard to debug this!

> Can you test with that (again with dbus disable) and report me if you
> are able to reproduce the issue ? If you are able to reproduce the
> issue, I would like to see the stack trace as usual. Thanks!
>

I can still reproduce the issue with that change.
Stack trace: https://paste.rs/mzY

**Comment by psibi** [comment]
@slotThe Nice, that's some improvement. :-) Can you try the same patched code with the following xmobarc configuration and see if you are able to reproduce it:
```
Config { lowerOnStart = True, commands = [] }
```
If you are not able to reproduce with the above configuration, then I would suggest you to just add `StdinReader` and see if't repeatable:
```
Config { lowerOnStart = True, commands = [Run StdinReader] }
```
and then try to add the date command:
```
Config { lowerOnStart = True,
              commands = [ Run $ Date "%a %b %_d %Y * %H:%M:%S" "theDate" 10
             , Run StdinReader]
```
I have a feeling one of the above commands is triggering the bug.

**Comment by psibi** [comment]
If all of them reproduces the bug, then I have to look into the stack trace and the xmboar's code more deeply.

**Comment by psibi** [comment]
@slotThe Also, if you are able to reproduce with either or some of them - I would like to see stack trace of each of them as that would give me quite a lot of information. Thanks!

**Comment by slotThe** [comment]
On Wed, May 13 2020 09:35, Sibi Prabakaran wrote:
> ```
> Config { lowerOnStart = True, commands = [] }
> ```
>

This just gets hung on trying to update the bar with useful information
(Updating...).  I suppose this is expected behaviour, as we don't have
anything to display and we're not actually reading anything from the
pipe that xmonad provides, hence we can't run out of things to read.

> ```
> Config { lowerOnStart = True, commands = [Run StdinReader] }
> ```
>

With this I can reproduce the issue (as now we are trying to read from
the named pipe).  Stack trace: https://paste.rs/Mrt

> and then try to add the date command:
> ```
> Config { lowerOnStart = True,
>               commands = [ Run $ Date "%a %b %_d %Y * %H:%M:%S" "theDate" 10
>              , Run StdinReader]
> ```
>

This also reproduces the issue.  Stack trace: https://paste.rs/oJI

> I have a feeling one of the above commands is triggering the bug.
>

Well, the bug is triggered while reading stdin so yes StdinReader will
probably have something to do with it ;)

**Comment by psibi** [comment]
@slotThe What if you are just using the date plugin and not the StdinReader ?

**Comment by slotThe** [comment]
On Wed, May 13 2020 12:08, Sibi Prabakaran wrote:
> [1]@slotThe What if you are just using the date plugin and not the
> StdinReader ?
>

Then the left aligned part of the bar (which in this case is only the
StdinReader) gets stuck on "Updating..." and the right aligned part (the
date) works.

**Comment by psibi** [comment]
@slotThe I have update the MR with some updates and logs: https://github.com/jaor/xmobar/pull/445

Can you re-compile your xmobar and produce the stack trace again.

**Comment by psibi** [comment]
Also, if you can just use the `StdinReader` plugin to reproduce the issue - that will be helpful. Thanks!

**Comment by slotThe** [comment]
On Wed, May 13 2020 19:23, Sibi Prabakaran wrote:
> [1]@slotThe I have update the MR with some updates and logs: [2]#445
>
> Can you re-compile your xmobar and produce the stack trace again.
>

Sure thing, here you go (this is with only StdinReader):
https://paste.rs/eyR

**Comment by psibi** [comment]
@slotThe I have updated the patch. Can you try it again ? This time you don't have to put any xmobar configuration anywhere. I have put some lots in the code which will be helpful in debugging. Let me know if you are able to reproduce ? Share the stack trace and `~/.xsession-errors` log. Thanks!

**Comment by slotThe** [comment]
On Fri, May 15 2020 10:03, Sibi Prabakaran wrote:
> @slotThe I have updated the patch. Can you try it again ? This time
> you don't have to put any xmobar configuration anywhere. I have put
> some lots in the code which will be helpful in debugging. Let me know
> if you are able to reproduce ? Share the stack trace and
> `~/.xsession-errors` log. Thanks!

Yes I can still reproduce it.  Stack trace: https://paste.rs/jTb

**Comment by psibi** [comment]
@slotThe That's Interesting. I falsely assumed before that we are receiving an asynchronous exception. But it seems that the issue is with having no data in the handle and waiting for 3 seconds doesn't matter in your configuration - which is very strange. 

I have create a minimal project here: https://github.com/psibi/xmobar-issue-exe

Can you follow the instructions in the README and tell me what you see in your system ? Thanks.

**Comment by donaldcallen** [comment]
I am running xmonad/xmobar on a FreeBSD 12.1 system and have been plagued by this problem to the point of about to switch back to dwm.

I just observed the problem with this .xmobarrc:

Config { font = "-misc-fixed-*-*-*-*-10-*-*-*-*-*-*-*"
       , additionalFonts = []
       , borderColor = "black"
       , border = TopB
       , bgColor = "black"
       , fgColor = "grey"
       , alpha = 255
       , position = Top
       , textOffset = -1
       , iconOffset = -1
       , lowerOnStart = False
       , pickBroadest = False
       , persistent = False
       , hideOnStart = False
       , iconRoot = "."
       , allDesktops = True
       , overrideRedirect = True
       , commands = [ Run Date "%A %Y-%m-%d %H:%M:%S%z" "date" 100 
						, Run StdinReader ]
       , sepChar = "%"
       , alignSep = "}{"
       , template = "%StdinReader%}{<fc=#ffff00>%date%</fc>"
       }

**Comment by jaor** [comment]
Sibi, slotThe, do you guys think we could revert the problematic
change in Stdinreader while we're debugging?  Just to avoid giving
trouble to users of master like @donaldcallen...

(BTW, i hugely appreciate the effort you're making to nail down the
real cause of the problem, please don't get me wrong!)

**Comment by jaor** [comment]
@donalcallen i've just pushed a patch that reverts temporarily (until
we find a real fix) StdinReader to its previous behaviour.

would you please confirm it fixes the issue for you if/when you can
try it? thanks!

**Comment by donaldcallen** [comment]
On Sun, 17 May 2020 at 18:51, jao <notifications@github.com> wrote:

> @donalcallen i've just pushed a patch that reverts temporarily (until
> we find a real fix) StdinReader to its previous behaviour.
>
> would you please confirm it fixes the issue for you if/when you can
> try it? thanks!
>

I tried building with stack, per the instructions,  and got the following
error:

cryptonite                       > [117 of 123] Compiling
Crypto.PubKey.ElGamal
cryptonite                       > [118 of 123] Compiling
Crypto.PubKey.ECC.DH
cryptonite                       > [119 of 123] Compiling
Crypto.ECC.Simple.Prim
cryptonite                       > [120 of 123] Compiling Crypto.ECC
X11                              > copy/register
X11                              > Installing library in
/usr/home/dca/.stack/snapshots/x86_64-freebsd-ino64/322d3308aff01fd94673334c8c6db13ec5b520e7f954c8e5ea8f5dfad6b6619b/8.6.5/lib/x86_64-freebsd-ghc-8.6.5/X11-1.9.1-4cKlus0ZOzs1Oj5QUWiq0P
X11                              > Registering library for X11-1.9.1..
cryptonite                       > [121 of 123] Compiling
Crypto.PubKey.ECIES
cryptonite                       > [122 of 123] Compiling Crypto.Data.AFIS
cryptonite                       > [123 of 123] Compiling Crypto.Tutorial
cryptonite                       > copy/register
cryptonite                       > Installing library in
/usr/home/dca/.stack/snapshots/x86_64-freebsd-ino64/322d3308aff01fd94673334c8c6db13ec5b520e7f954c8e5ea8f5dfad6b6619b/8.6.5/lib/x86_64-freebsd-ghc-8.6.5/cryptonite-0.25-GRKCG37cD79GVqvGPiaNxJ
cryptonite                       > Registering library for cryptonite-0.25..

--  While building package netlink-1.1.1.0 using:

/usr/home/dca/.stack/setup-exe-cache/x86_64-freebsd-ino64/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5
--builddir=.stack-work/dist/x86_64-freebsd-ino64/Cabal-2.4.0.1 build
--ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
Progress 45/113
dca@igor:/tmp/xmobar$

stack had previously suggested adding the second extra-dep to stack.yaml:

extra-deps:
 - netlink-1.1.1.0
 - bsd-sysctl-1.0.8.0@sha256
:4d57c7e8f24da255f7158c95e1b06dd06a6e3e204702208317d5390c39768efe,1291

This is on a FreeBSD 12.1 system. I do have Linux installed on a couple of
machines, Slackware current. I'll give it try to see if this error is
FreeBSD-specific and get back to you.

/Don

**Comment by jaor** [comment]
thanks, @donalcallen ... this has me scratching my head: was the
previous version in the repo (without the latest "fix" of mine)
compiling cleanly?

**Comment by donaldcallen** [comment]
On Sun, 17 May 2020 at 20:16, jao <notifications@github.com> wrote:

>
> thanks, @donalcallen ... this has me scratching my head: was the
> previous version in the repo (without the latest "fix" of mine)
> compiling cleanly?
>

No. Same error. I would have opened a new issue if this conversation hadn't
come up.

**Comment by jaor** [comment]
On Sun, May 17 2020, donaldcallen wrote:

> On Sun, 17 May 2020 at 20:16, jao <notifications@github.com> wrote:
>
>>
>> thanks, @donalcallen ... this has me scratching my head: was the
>> previous version in the repo (without the latest "fix" of mine)
>> compiling cleanly?
>>
>
> No. Same error. I would have opened a new issue if this conversation hadn't
> come up.

oh, i thoght you were experiencing the StdinReader problem discussed in
this issue.  isn't that the case then?

**Comment by donaldcallen** [comment]
On Sun, 17 May 2020 at 20:56, jao <notifications@github.com> wrote:

> On Sun, May 17 2020, donaldcallen wrote:
>
> > On Sun, 17 May 2020 at 20:16, jao <notifications@github.com> wrote:
> >
> >>
> >> thanks, @donalcallen ... this has me scratching my head: was the
> >> previous version in the repo (without the latest "fix" of mine)
> >> compiling cleanly?
> >>
> >
> > No. Same error. I would have opened a new issue if this conversation
> hadn't
> > come up.
>
> oh, i thoght you were experiencing the StdinReader problem discussed in
> this issue. isn't that the case then?
>

Yes, I am experiencing the problem being discussed here. But FreeBSD's
repository is one xmobar version behind  the current version (they provide
.32 in their repository), so
I tried to build the latest version, .33 by downloading from github and
building with stack, that resulted in the same  error I just sent you. That
was much earlier today, before you installed your
latest patch. So, to be clear, I have gotten that same error on FreeBSD
twice -- once before and once after you installed your patch

As I promised, i just tried building on Slackware Linux with stack and the
latest on github. Different error:

Cabal                            > [214 of 220] Compiling
Distribution.Simple.Bench
Cabal                            > [215 of 220] Compiling
Distribution.Simple.SrcDist
Cabal                            > [216 of 220] Compiling
Distribution.Simple.Configure
Cabal                            > [217 of 220] Compiling
Distribution.Simple.Build
Cabal                            > [218 of 220] Compiling
Distribution.Simple.Haddock
Cabal                            > [219 of 220] Compiling
Distribution.Simple.Doctest
Cabal                            > [220 of 220] Compiling
Distribution.Simple
Cabal                            > copy/register
Cabal                            > Installing library in
/home/dca/.stack/snapshots/x86_64-linux-tinfo6/82a00b3dc635c38d25c90e577e4ca96de03afe3d3cbab8a25f8556622e97e84f/8.6.5/lib/x86_64-linux-ghc-8.6.5/Cabal-2.4.1.0-3JC906oWQ73Ah7bYkIcI4J
Cabal                            > Registering library for Cabal-2.4.1.0..
HttpExceptionRequest Request {
  host                 = "s3.amazonaws.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","Haskell pantry package")]
  path                 = "/
hackage.fpcomplete.com/package/http-client-0.6.4.tar.gz"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.getAddrInfo (called with preferred
socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily =
AF_UNSPEC, addrSocketType = Stream, addrProtocol = 6, addrAddress =
<assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host
name: Just "s3.amazonaws.com", service name: Just "443"): does not exist
(Try again))
Progress 83/112
dca@giovanni:/tmp/xmobar$

**Comment by jaor** [comment]
On Sun, May 17 2020, donaldcallen wrote:

> Cabal > [214 of 220] Compiling
> Distribution.Simple.Bench
> Cabal > [215 of 220] Compiling
> Distribution.Simple.SrcDist
> Cabal > [216 of 220] Compiling
> Distribution.Simple.Configure
> Cabal > [217 of 220] Compiling
> Distribution.Simple.Build
> Cabal > [218 of 220] Compiling
> Distribution.Simple.Haddock
> Cabal > [219 of 220] Compiling
> Distribution.Simple.Doctest
> Cabal > [220 of 220] Compiling
> Distribution.Simple
> Cabal > copy/register
> Cabal > Installing library in
> /home/dca/.stack/snapshots/x86_64-linux-tinfo6/
> 82a00b3dc635c38d25c90e577e4ca96de03afe3d3cbab8a25f8556622e97e84f/8.6.5/lib/x86_64-linux-ghc-8.6.5/
> Cabal-2.4.1.0-3JC906oWQ73Ah7bYkIcI4J
> Cabal > Registering library for Cabal-2.4.1.0..
> HttpExceptionRequest Request {
> host = "s3.amazonaws.com"
> port = 443
> secure = True
> requestHeaders = [("User-Agent","Haskell pantry package")]
> path = "/
> hackage.fpcomplete.com/package/http-client-0.6.4.tar.gz"
> queryString = ""
> method = "GET"
> proxy = Nothing
> rawBody = False
> redirectCount = 10
> responseTimeout = ResponseTimeoutDefault
> requestVersion = HTTP/1.1
> }
> (ConnectionFailure Network.Socket.getAddrInfo (called with preferred
> socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily =
> AF_UNSPEC, addrSocketType = Stream, addrProtocol = 6, addrAddress =
> <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host
> name: Just "s3.amazonaws.com", service name: Just "443"): does not exist
> (Try again))
> Progress 83/112
> dca@giovanni:/tmp/xmobar$

hmmm.  as far as i can tell, those are network errors, either on you
side or hackage's, whereby you cannot access hackage to build packages.
they don't seem related to xmobar per se...

**Comment by donaldcallen** [comment]
On Sun, 17 May 2020 at 21:32, jao <notifications@github.com> wrote:

> On Sun, May 17 2020, donaldcallen wrote:
>
>
>
> hmmm. as far as i can tell, those are network errors, either on you
> side or hackage's, whereby you cannot access hackage to build packages.
> they don't seem related to xmobar per se...
>

I agree. It's odd, because it was chugging away, building a lot of stuff
before it collapsed.

The whole Haskell thing is really beginning to feel like an exercise in
futility. There's just too much machinery, too many
moving parts. If you need me to try to build on my Linux system for
debugging purposes, I'll give it another try tomorrow. But that's
not going to solve the FreeBSD problem and FreeBSD is my primary system;
it's where I do my work. So I've installed another window manager (fvwm3)
there that works well. I also have the option of going back to dwm, though
dwm lacks some things that I really would like to have, such as
minimization. It was exactly
that issue that prompted me to give xmonad another try, but without a
working xmobar, it's useless to me and I can't build your patched version.

/Don

**Comment by jaor** [comment]
i see how this can be frustrating, specially if all you care about is
xmobar; building it requires an amount of machinery that is difficult to
bear with.

maybe you just were unlucky today, and caught some site downtime or
maintenance (they happen seldom, in my experience), and tomorrow things
will build again... as an aside, using stack for the compilation is not
required, `cabal install` (with cabal 3.x), works well for me (and it's
one less moving piece).

**Comment by psibi** [comment]
@jaor Given donalcallen's message - it seems he is reproducing the issue in xmobar 0.32. So I'm not sure if reverting it will make it work for him. But it's okay to have this commit reverted in master untill I figure things out with slotThe.

@slotThe I have updated the MR again to see if it makes it work. Let me know if the  updated MR does change anything. Thanks for your effort so far in helping us debug this issue.

**Comment by slotThe** [comment]
On Sun, May 17 2020 10:47, Sibi Prabakaran wrote:
> I have create a minimal project here: 
> https://github.com/psibi/xmobar-issue-exe
>

This just prints "hello-world" a whole bunch of times, no errors occur.

On Mon, May 18 2020 00:31, jao wrote:
> Sibi, slotThe, do you guys think we could revert the problematic
> change in Stdinreader while we're debugging?  Just to avoid giving
> trouble to users of master like @donaldcallen...
>

This sounds sensible to me, at least until we've nailed down this 
issue, which we do seem to be pretty close to.

On Mon, May 18 2020 05:49, Sibi Prabakaran wrote:
> @slotThe I have updated the MR again to see if it makes it work. Let
> me know if the  updated MR does change anything. Thanks for your
> effort so far in helping us debug this issue.
>

This works!  I don't know how bailing out immediately would have this 
effect, but it does either way.

**Comment by psibi** [comment]
@slotThe Awesome!

This was my thought pattern: I was wondering from your debugging, how could the earlier buggy code work. Your log indicated that no matter what, the EOF exception is getting raised - in spite of delaying 3 seconds and trying again. So, it seems in the earlier working case - we are just bailing out at the end. But with my exception handling , we weren't bailing and throwing the exception. So adding that has made it work.

@jaor With help from @slotThe we have figured out a fix which works. I will be sending a MR by today or tomorrow. Thanks @slotThe for your help. Couldn't have found a solution without your patience and debugging skills. :-) I will still need your testing once I create a fresh MR for it. Thanks!

**Comment by donaldcallen** [comment]
Build on FreeBSD fails like so:
dca@franz:/tmp/xmobar$ stack build
netlink             > configure
netlink             > Configuring netlink-1.1.1.0...
netlink             > build
network-uri         > configure
netlink             > Preprocessing library for netlink-1.1.1.0..
netlink             >
/tmp/stack-ffda5e56cd6fbf21/netlink-1.1.1.0/C.hsc:48:10: fatal error:
linux/netlink.h: No such file or directory
<<<<<<<<<<<<<<<<<<<<<<<<<----------------------------------------
netlink             > compilation terminated.
netlink             > compiling
.stack-work/dist/x86_64-freebsd-ino64/Cabal-2.4.0.1/build/System/Linux/Netlink/C_hsc_make.c
failed (exit code 1)
netlink             > command was: /usr/local/bin/gcc -c
.stack-work/dist/x86_64-freebsd-ino64/Cabal-2.4.0.1/build/System/Linux/Netlink/C_hsc_make.c
-o
.stack-work/dist/x86_64-freebsd-ino64/Cabal-2.4.0.1/build/System/Linux/Netlink/C_hsc_make.o
-fno-stack-protector -fno-stack-protector -fuse-ld=lld
-D__GLASGOW_HASKELL__=806 -Dfreebsd_BUILD_OS=1 -Dx86_64_BUILD_ARCH=1
-Dfreebsd_HOST_OS=1 -Dx86_64_HOST_ARCH=1
-I.stack-work/dist/x86_64-freebsd-ino64/Cabal-2.4.0.1/build/autogen
-I.stack-work/dist/x86_64-freebsd-ino64/Cabal-2.4.0.1/build/global-autogen
-include
.stack-work/dist/x86_64-freebsd-ino64/Cabal-2.4.0.1/build/autogen/cabal_macros.h
-I/usr/home/dca/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.5/lib/ghc-8.6.5/unix-2.7.2.2/include
-I/usr/home/dca/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.5/lib/ghc-8.6.5/time-1.8.0.2/include
-I/usr/home/dca/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.5/lib/ghc-8.6.5/bytestring-0.10.8.2/include
-I/usr/local/include
-I/usr/home/dca/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.5/lib/ghc-8.6.5/base-4.12.0.0/include
-I/usr/local/include
-I/usr/home/dca/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.5/lib/ghc-8.6.5/integer-gmp-1.0.2.0/include
-I/usr/home/dca/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.5/lib/ghc-8.6.5/include
-I/usr/local/include
-I/usr/home/dca/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.5/lib/ghc-8.6.5/include/
network-uri         > Configuring network-uri-2.6.1.0...


Seems to be a Linux dependency buried in this. I am going to have to move
on.

/Don

**Comment by slotThe** [comment]
On Mon, May 18 2020 16:06, donaldcallen wrote:
> /tmp/stack-ffda5e56cd6fbf21/netlink-1.1.1.0/C.hsc:48:10: fatal error:
> linux/netlink.h: No such file or directory
>

This is due to the new `nl80211` module for wifi.  You can use the old,
iwlib-based solution by setting `with_nl80211` to False and `with_iwlib`
to True.

**Comment by donaldcallen** [comment]
Well, it turned out that neither fvwm2 nor its re-write are reliable. Which
provided motivation to use the information you gave me to try to get xmobar
built (from the current master version on github) on my FreeBSD system,
which I did (by eliminating both wifi options, since I don't need them). I
then brought up xmonad using that xmobar.
This version of xmonad does not attempt to make the workspace names
clickable. I used the system for a bit and then left to have a glass of
wine with my wife. When I came back, same problem -- workspace names gone,
no window title or layout name displayed. And if I go to the console where
I did the startx, it's the old problem -- hgetline: invalid argument
(invalid byte sequence). So I don't think, despite your efforts, for which
I am
grateful, that you've solved this one yet.

**Comment by psibi** [comment]
@donaldcallen 

>  that you've solved this one yet.

I think you need to create a new issue with your xmonad details as the issue you are facing seems to be different that the one in the issue. But I recently fixed a similar issue in xmonad-contrib.

**Comment by psibi** [comment]
@slotThe Can you check with this MR: https://github.com/jaor/xmobar/pull/448
