### ISSUE TITLE
Reported volume is inaccurate with Pipewire

### ISSUE THREAD

**Issue by samhh** [jaor/xmobar#535]
In the status bar with `<volume>` I see `4` but the value is more like 35% in pavucontrol, and I think the latter is more accurate on the basis of what happens when I run `pactl set-sink-volume`.

This can either be interpreted as a bug in the Volume monitor or a feature request for a Pipewire monitor. :slightly_smiling_face:

**Comment by jaor** [comment]
i'm marking it as a feature request, to be on the bright side :)

**Comment by samhh** [comment]
Putting this comment here to help others who might have the same problem today.

After upgrading a few Arch deps and rebooting, specifically:

- pipewire (1:0.3.30-2 -> 1:0.3.31-1)
- pipewire-media-session (1:0.3.30-2 -> 1:0.3.31-1)
- pipewire-alsa (1:0.3.30-2 -> 1:0.3.31-1)
- pipewire-pulse (1:0.3.30-2 -> 1:0.3.31-1)

I was no longer able to start xmobar (via a custom executable), with a SIGSEGV / segmentation fault error. Remove the volume part of the config and recompile to workaround it.

**Comment by xla** [comment]
Running into the same issue as @samhh

**Comment by thisisjakeboyce** [comment]
Also having the same issue as @samhh

It was driving me crazy until I found this!

**Comment by ueXIMcWizBrdyVEciAlSwxP8aaXP70mO** [comment]
I want to add my observations while using xmobar with pipewire+ALSA. When I first start xmonad (and hence xmobar via `XMonad.Hooks.DynamicBars#dynStatusBarStartup`), my xmobar processes dump core. The core file points to an error when calling `libasound#snd_mixer_selem_get_id`. I have not had the chance to debug this any further. N.b., after the initial core dump, I can get xmobar running by reloading xmonad.

For posterity, I will also add some notes regarding xmobar's behavior with pipewire+ALSA. I do not think the following are xmobar problems; these seem more to do with the ALSA shim over pipewire, since e.g. `amixer` shows the same behavior as xmonad.

If nothing is producing sound, volume is reported as `0%`. Starting an audio stream, however, will enable the audio control. It looks like pipewire advertises a device to ALSA only when there is an active audio stream. Audio controls remain responsive until the application owning the audio stream exits. At this point, the volume stays frozen.

**Comment by a5ob7r** [comment]
> Putting this comment here to help others who might have the same problem today.
> 
> After upgrading a few Arch deps and rebooting, specifically:
> 
>     * pipewire (1:0.3.30-2 -> 1:0.3.31-1)
> 
>     * pipewire-media-session (1:0.3.30-2 -> 1:0.3.31-1)
> 
>     * pipewire-alsa (1:0.3.30-2 -> 1:0.3.31-1)
> 
>     * pipewire-pulse (1:0.3.30-2 -> 1:0.3.31-1)
> 
> 
> I was no longer able to start xmobar (via a custom executable), with a SIGSEGV / segmentation fault error. Remove the volume part of the config and recompile to workaround it.

This problem has been fixed by updating pipwire and related packages to new version in my arch linux environment🎉.

     * pipewire (1:0.3.31-1 -> 1:0.3.32-1)

     * pipewire-media-session (1:0.3.31-1 -> 1:0.3.32-1)

     * pipewire-alsa (1:0.3.31-1 -> 1:0.3.32-1)

     * pipewire-pulse (1:0.3.31-1 -> 1:0.3.32-1)

Maybe thanks to this fix.

> ## ALSA plugin
>   - The alsa plugin now uses the right metadata for finding the default
>     source and sink, which makes the volume controls reappear. (#1384)

https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/4c166709d06571b889a89812c962a91ba4d0a071/NEWS

**Comment by vifon** [comment]
I believe it's caused by PipeWire using linear volume and PulseAudio using cubic volume ([source](https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.14)). The PulseAudio tools indeed see the "old" volume while the tools using the ALSA APIs see the linear one, like xmobar.

**Comment by yusi1** [comment]
This issue is now fixed with the latest version of Pipewire 0.3.44, here's the changelog..
https://gitlab.freedesktop.org/pipewire/pipewire/-/raw/master/NEWS

Relevant bit of changelog:
"Do the conversion between PulseAudio cubic volumes and PipeWire
linear volumes. Volume levels should behave now like they did
with PulseAudio."

Now XMobar shows the correct volume!

**Comment by jaor** [comment]
excellent, thanks a lot for reporting back!

**Comment by samhh** [comment]
I'm still seeing 4% with both `Volume` and `Alsa` monitors where `pavucontrol` reports 34%. Pipewire version 0.3.44. :thinking:

**Comment by yusi1** [comment]
> I'm still seeing 4% with both `Volume` and `Alsa` monitors where `pavucontrol` reports 34%. Pipewire version 0.3.44. thinking

Strange.. For me on Void Linux it seems to be fixed, just had to update..
